// Generated by gencpp from file rover_20_control/Arm_msgs.msg
// DO NOT EDIT!


#ifndef ROVER_20_CONTROL_MESSAGE_ARM_MSGS_H
#define ROVER_20_CONTROL_MESSAGE_ARM_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_20_control
{
template <class ContainerAllocator>
struct Arm_msgs_
{
  typedef Arm_msgs_<ContainerAllocator> Type;

  Arm_msgs_()
    : joint0(0.0)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
    }
  Arm_msgs_(const ContainerAllocator& _alloc)
    : joint0(0.0)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
  (void)_alloc;
    }



   typedef double _joint0_type;
  _joint0_type joint0;

   typedef double _joint1_type;
  _joint1_type joint1;

   typedef double _joint2_type;
  _joint2_type joint2;

   typedef double _joint3_type;
  _joint3_type joint3;

   typedef double _joint4_type;
  _joint4_type joint4;

   typedef double _joint5_type;
  _joint5_type joint5;

   typedef double _joint6_type;
  _joint6_type joint6;





  typedef boost::shared_ptr< ::rover_20_control::Arm_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_20_control::Arm_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_msgs_

typedef ::rover_20_control::Arm_msgs_<std::allocator<void> > Arm_msgs;

typedef boost::shared_ptr< ::rover_20_control::Arm_msgs > Arm_msgsPtr;
typedef boost::shared_ptr< ::rover_20_control::Arm_msgs const> Arm_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_20_control::Arm_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_20_control::Arm_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_20_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rover_20_control': ['/home/basestation/rover20_ws/src/rover_20/rover_20_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_20_control::Arm_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_20_control::Arm_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_20_control::Arm_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4515360d2b590c5a38f3e5678e7e9266";
  }

  static const char* value(const ::rover_20_control::Arm_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4515360d2b590c5aULL;
  static const uint64_t static_value2 = 0x38f3e5678e7e9266ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_20_control/Arm_msgs";
  }

  static const char* value(const ::rover_20_control::Arm_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64  joint0\n\
float64 joint1\n\
float64 joint2\n\
float64  joint3\n\
float64  joint4\n\
float64  joint5\n\
float64  joint6\n\
";
  }

  static const char* value(const ::rover_20_control::Arm_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint0);
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.joint5);
      stream.next(m.joint6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_20_control::Arm_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_20_control::Arm_msgs_<ContainerAllocator>& v)
  {
    s << indent << "joint0: ";
    Printer<double>::stream(s, indent + "  ", v.joint0);
    s << indent << "joint1: ";
    Printer<double>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<double>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<double>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<double>::stream(s, indent + "  ", v.joint4);
    s << indent << "joint5: ";
    Printer<double>::stream(s, indent + "  ", v.joint5);
    s << indent << "joint6: ";
    Printer<double>::stream(s, indent + "  ", v.joint6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_20_CONTROL_MESSAGE_ARM_MSGS_H
