footprint: [[-0.4, -0.4], [-0.4, 0.4], [0.4, 0.4], [0.4, -0.4]] #0.45, 0.66
footprint_padding: 0.01 #0.01

robot_base_frame: base_link
update_frequency: 4.0 #4.0
publish_frequency: 3.0 #3.0
transform_tolerance: 0.5 #0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0 #6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser #point_cloud_sensor
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1 #5
    cost_scaling_factor: 20

#    observation_sources: laser
#    laser: {sensor_frame: laser, clearing: true, topic: /scan, data_type: LaserScan, marking: true, min_obstacle_height: 0.1, inf_is_valid: true}
#point_cloud_sensor: {sensor_frame: laser, clearing: true, topic: /sick_mrs1000/cloud, data_type: PointCloud2, marking: true, min_obstacle_height: 0, max_obstacle_height: 0.03}

#  data_type: PointCloud2
#  marking: true, min_obstacle_height: 0.3
