# Publish all joint states -----------------------------------
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

# Position Controllers ---------------------------------------
rover_arm_j1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}
rover_arm_j2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}
rover_arm_j3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}
rover_arm_j4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}
rover_arm_j5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 1000,  d: 10, i: 0.1, i_clamp: 1}
rover_arm_j6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 10,  d: 0.1, i: 0.001, i_clamp: 1}