rate: 10 
controller_list:
  - name: fake_arm_20_controller
    type: interpolate | via points | last point
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

gains: # Required because we're controlling an effort interface
    joint_1: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint_2: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint_3: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint_4: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint_5: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint_6: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint_7: {p: 100,  d: 10, i: 0.01, i_clamp: 1}


constraints:
    joint_1:
      goal: 0.1
    joint_2:
      goal: 0.1
    joint_3:
      goal: 0.1
    joint_4:
      goal: 0.1
    joint_5:
      goal: 0.1
    joint_6:
      goal: 0.1
    joint_7:
      goal: 0.1
    goal_time: 100
